# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Ujamaa Pool
# Description of the Site
description: Our stake pool builds and maintains the Cardano network for us and generates ADA rewards from it together
# URL of Image of the Site
site-image: https://ujamaapool.com/assets/images/logo.png
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: https://ujamaapool.com/assets/images/logo.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://ujamaapool.com/assets/images/hero-image.jpeg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: ujamaa.pool@mailfence.com
#facebook_username: wearetech4youth
#twitter_username: wearetech4youth
#instagram_username: wearetech4youth
#linkedin_username: oedwards
#github_username: skibbler
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
#disqus-shortname: thedevslot

# Name of the Author
author-name: Ujamaa Pool
# URL for the Image of the Author
author-image: https://ujamaapool.com/assets/images/logo.png
###https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about-1: Ujamaa stands for "Cooperative Economics".
author-about-2: The term means that we build and maintain our own stores, shops, and other businesses and profit from them together.
author-about-3: With the Cardano network, we have taking this same stance - where we help build and maintain the Cardano network and provide ADA rewards that allow us to profit from the network together. Join the journey with us!
#author-about-3:
### At Ujamaa Pool we are committed to providing top quality ADA staking services to all of our delegates. We practice continual improvement to maximize pool efficiency in block producing capability and transaction processing. This allows us to provide competitive returns for our delegates while maintaining the most secure, distributed network of nodes, paired with our 24 / 7 / 365 reliable performance.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/skibbler

#Pool info
pool-name: Ujamaa Stake Pool
pool-ticker: UJMA
pool-id: 14c3e145e04b50ec3b3fadd60dbba14ed577d37f8a96b59c53cb1625

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
